language: python
python:
  - "2.7"
before_install:
  - git fetch origin master:refs/remotes/origin/master
install:
  - make requirements
  - pip install coveralls
script:
  - make test
  - make quality
after_success:
  - coveralls
