language: python
python:
  - "2.7"
install:
  - pip install -r test-requirements.txt 
  - pip install coveralls
script:
  - coverage run -m nose
  - pep8
  - script/max_pylint_violations 20
after_success:
  - coveralls
