language: python
python:
  - "2.7"
before_install:
  - git fetch origin master:refs/remotes/origin/master
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - scripts/coverage
  - scripts/quality
  - scripts/max_pep8_violations 1
  - scripts/max_pylint_violations 45
after_success:
  - coveralls
